services:
  mysql:
    container_name: mysql8
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes: 
      - type: bind
        source: ./data/mysql8
        target: /var/lib/mysql
        read_only: false
    networks:
      - mysql-development

networks:
  mysql-development:
    name: mysql-development
    driver: bridge