services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    user: root
    environment:
      - GENERIC_TIMEZONE=Asia/Bangkok
      - TZ=Asia/Bangkok
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_test
      - DB_POSTGRESDB_USER=root
      - DB_POSTGRESDB_PASSWORD=root
    ports:
      - 5678:5678
    volumes:
      - ./data/n8n:/home/node/.n8n
    networks:
      - postgres-development

networks:
  postgres-development:
    external: true
