services:
  redis:
    container_name: redis-latest
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: on-failure
    volumes:
      - type: bind
        source: ./config/redis-latest/redis.conf
        target: /usr/local/etc/redis/redis.conf
        read_only: true
      - type: bind 
        source: ./data/redis-latest
        target: /data
        read_only: false
    # Set up a network to allow other containers to connect to the MySQL container if needed.
    networks:
      - redis-development

networks:
  redis-development:
    name: redis-development
    driver: bridge

